### PR TITLE
Use vapply instead of sapply

### PR DESCRIPTION
**Pull request by jwpestrak**
At least one major R contributor - Hadley Wickham - has advised against using sapply in functions. Instead he advocates lapply or vapply. 

See
https://twitter.com/hadleywickham/status/434339083871993856
http://stackoverflow.com/questions/12339650/why-is-vapply-safer-than-sapply

### CODE REVIEW

**Comment by jread-usgs** [comment]
:+1:

**Comment by ldecicco-USGS** [comment]
Looks good, thanks!

**Comment by ldecicco-USGS** [comment]
@jwpestrak : Let me know if you want to be listed as a Contributor


"Authors who have made
smaller contributions (such as code patches
etc.) but should not show up in the package
citation."

**Comment by jwpestrak** [comment]
@ldecicco-USGS No need to list me as a Contributor. If I make some more (substantial) changes, then I might ask to be listed.  Just happy to help!

**Pull request merged**
