### PR TITLE
Fixed bug in drURL function

### PR DESCRIPTION
**Pull request by veronikayurchuk**
The bug gave an error **"Error in as.vector(x, "character") : 
  cannot coerce type 'externalptr' to vector of type 'character'"** when calling a **whatNWISsites** function

### CODE REVIEW

**Comment by jread-usgs** [comment]
I ran into that bug too, but I don't think these changes address it.

**Comment by veronikayurchuk** [comment]
Hi @jread-usgs !

Function drURL is inside whatNWISsites function. When we call drURL function using for example stateCd="OH",parameterCd=p_code, the output is _"?format=mapper&stateCd=OH&parameterCd=00065"_ instead of _"http://waterservices.usgs.gov/nwis/site/?format=mapper&stateCd=OH&parameterCd=00065"!_

The reason of the problem is in the following code from the drURL function: _return(paste0(pkg.env[[base.name]], '?', queryString))_, it means that_ pkg.env[[base.name]]_, where base.name = 'waterservices' gave "".

One of the possible solution is to define pkg.env$waterservices inside the function drURL. As the result the output of drURL function gave "http://waterservices.usgs.gov/nwis/site/?format=mapper&stateCd=OH&parameterCd=00065"

**Comment by ldecicco-USGS** [comment]
@veronikayurchuk : Could you install from gitHub right now (before your pull request) and verify the bug is still there? I put in a fix to this bug a few days ago to gitHub, and if you are still seeing the error, we'll need to see a reproducible example. So:

```
devtools::install_github("USGS-R/dataRetrieval")
library(dataRetrieval)
OHsites <- whatNWISsites(stateCd="OH",parameterCd="00065")

```

This example works with what is currently up on gitHub. I plan to push it off to CRAN in the next couple of days.

**Comment by veronikayurchuk** [comment]
Hi @ldecicco-USGS !
It works fine!

**Comment by ldecicco-USGS** [comment]
Great. Thanks for checking and digging into the code. I really appreciate it.

**Pull request closed without merging**
