### PR TITLE
Bug fix

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by jiwalker-usgs** [comment]
Tests may be failing now?

**Comment by ldecicco-USGS** [comment]
I'm getting some 503's on NWIS right now. I have a few more fixes to push too though from all these pr merges.

**Comment by ldecicco-USGS** [comment]
Just have to figure out what's going on with NGWMN now.

**Comment by ldecicco-USGS** [comment]
NGWMN tests seem to intermittently fail on my computer (and pass). I'm going to merge this to get the bug fix in there, but keep having a look at the groundwater functions, see if there's anything we can do.

**Pull request merged**
