### PR TITLE
gwlevels to rdb

### PR DESCRIPTION
**Pull request by ldecicco-USGS**
and space in parameterCd if characteristic name.

### CODE REVIEW

**Comment by lawinslow** [comment]
Minor version increment?

**Comment by ldecicco-USGS** [comment]
You want 2.4.0?

**Comment by ldecicco-USGS** [comment]
Whoops! Yeah, I wanted it to be in the 2.3s

**Comment by ldecicco-USGS** [comment]
Dang nammit, more waiting.

**Comment by lawinslow** [comment]
Yeah, was just thinking 2.3.1 or whatever. Just something so I know when I have this version installed.

**Pull request merged**
